version: '2'
services:
  eventstore-master:
    image: registry.viareport.com:8080/inativ/eventstore-manager:cluster
    environment:
      EVENTSTORE_CLUSTER_SIZE: ${cluster_size}
      NODE_PRIORITY: ${cluster_size}
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  dns:
    image: rancher/dns-service
    links:
    - eventstore-node:eventstore-node
  eventstore-node:
    image: registry.viareport.com:8080/inativ/eventstore:cluster
    environment:
      EVENTSTORE_CLUSTER_SIZE: ${cluster_size}
    stdin_open: true
    volumes:
    - ${volume_data}:/var/lib/eventstore
    - ${volume_log}:/var/log/eventstore
    tty: true
    labels:
      io.rancher.container.pull_image: always