version: '2'
services:
  eventstore-master:
    image: registry.viareport.com:8080/inativ/eventstore-cluster:3.9.3
    environment:
      EVENTSTORE_CLUSTER_SIZE: ${cluster_size+1}
      NODE_PRIORITY: ${cluster_size}
    stdin_open: true
    volumes:
    - ${volume_data}:/var/lib/eventstore
    - ${volume_log}:/var/log/eventstore
    tty: true
    labels:
      io.rancher.container.pull_image: always
  eventstore-node:
    image: registry.viareport.com:8080/inativ/eventstore-cluster:3.9.3
    environment:
      EVENTSTORE_CLUSTER_SIZE: ${cluster_size+1}
    stdin_open: true
    volumes:
    - ${volume_data}:/var/lib/eventstore
    - ${volume_log}:/var/log/eventstore
    tty: true
    labels:
      io.rancher.container.pull_image: always
    links:
    - eventstore-master:dns