.catalog:
  name: "Elasticsearch-cluster"
  description: "Cluster using elasticsearch in version 5.2.2 with log redirection to UDP host"
  version: "5.2.2-1"
  upgrade_from: "1"
  questions:
    - variable: "cluster_size"
      description: "The number of nodes in the cluster."
      label: "Cluster size"
      type: "int"
      default: "3"
      required : true
    - variable: "cluster_name"
      description: "The name of the cluster."
      label: "Cluster name"
      type: "string"
      required : true
    - variable: "volume_log"
      description: "Path where to keep log files. (Host path)"
      label: "Log"
      type: "string"
      default: "/data/elasticsearch-cluster/log"
      required : true
    - variable: "volume_data"
      description: "Path where to keep data files. (Host path)"
      label: "Data"
      type: "string"
      default: "/data/elasticsearch-cluster/data"
      required : true
    - variable: "autocreate_index"
      description: "Defines which indices should be automatically created"
      label: "Index auto create"
      type: "string"
      default: "+.*,-*"
      required: true
    - variable: "security_enabled"
      description: "Elasticsearch xpack security enabled"
      label: "Security enabled"
      type: "boolean"
      default: true
      required: true
    - variable: "data_jvm_memory"
      description: "Elasticsearch data nodes JVM memory"
      label: "Data node JVM memory"
      type: "string"
      default: "1g"
      required: true
    - variable: "master_jvm_memory"
      description: "Elasticsearch master node JVM memory"
      label: "Master node JVM memory"
      type: "string"
      default: "512m"
      required: true
    - variable: "plateforme_env"
      description: "Environment type of the platform (ex dev, preprod or prod)"
      label: "Platform environment"
      type: "string"
      default: "devel"
      required: true
    - variable: "log_udp_host"
      description: "Host udp listener for logs centralization"
      label: "Log UDP host"
      type: "string"
      default: "192.168.1.137"
      required: true

version: '2'
services:
  data:
    scale: ${cluster_size}
    start_on_create: true
  kibana:
    scale: 1
    start_on_create: true
  master:
    scale: 1
    start_on_create: true

