version: '2'
services:
  data-nodes:
    mem_limit: 1048576000
    cap_add:
    - IPC_LOCK
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      bootstrap.memory_lock: 'true'
      cluster.name: ${cluster_name}
      discovery.zen.ping.unicast.hosts: master-node
      node.master: 'false'
      xpack.security.enabled: 'false'
      action.auto_create_index: '+.*,-*'
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - ${volume_log}/${cluster_name}/data:/var/log/elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.2
    environment:
      xpack.security.enabled: 'false'
    stdin_open: true
    tty: true
    links:
    - master-node:elasticsearch
    labels:
      io.rancher.container.pull_image: always
  master-node:
    mem_limit: 1048576000
    cap_add:
    - IPC_LOCK
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      bootstrap.memory_lock: 'true'
      cluster.name: ${cluster_name}
      node.data: 'false'
      xpack.security.enabled: 'false'
      action.auto_create_index: '+.*,-*'
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - ${volume_log}/${cluster_name}/master:/var/log/elasticsearch

