.catalog:
  name: "EventStore-cluster"
  version: "0"
  questions:
    - variable: "cluster_size"
      description: "The number of nodes in the cluster."
      label: "Cluster size"
      type: "int"
      default: "3"
      required : true
    - variable: "cluster_name"
      description: "The name of the cluster."
      label: "Cluster name"
      type: "string"
      required : true
    - variable: "volume_log"
      description: "Path where to keep log files. (Host path)"
      label: "Log"
      type: "string"
      default: "/opt/elasticsearch-cluster/log"
      required : true
    - variable: "autocreate_index"
      description: "Defines which indices should be automatically created"
      label: "Index auto create"
      type: "string"
      default: "+.*,-*"
      required: true
    - variable: "security_enabled"
      description: "Elasticsearch xpack security enabled"
      label: "Security enabled"
      type: "boolean"
      default: true
      required: true
    - variable: "data_jvm_memory"
      description: "Elasticsearch data nodes JVM memory"
      label: "Data node JVM memory"
      type: "string"
      default: "1g"
      required: true
    - variable: "master_jvm_memory"
      description: "Elasticsearch master node JVM memory"
      label: "Master node JVM memory"
      type: "string"
      default: "512m"
      required: true

version: '2'
services:
  data:
    scale: ${cluster_size}
    start_on_create: true
  kibana:
    scale: 1
    start_on_create: true
  master:
    scale: 1
    start_on_create: true

